projects:
  testchattool-test:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: ap-northeast-1
        apiId: zjldbd6545hsthsbivlyuz6qea
        maxDepth: 2
extensions:
  amplify:
    version: 3
